class AddMissingOrderAndPaymentColumns < ActiveRecord::Migration[7.1]
  def change
    # ===== ORDERS =====
    add_column :orders, :order_type, :string unless column_exists?(:orders, :order_type)
    add_column :orders, :exchange_order_number, :string unless column_exists?(:orders, :exchange_order_number)
    add_column :orders, :shipping_mode, :string unless column_exists?(:orders, :shipping_mode)
    add_column :orders, :instado, :boolean, default: false unless column_exists?(:orders, :instado)
    add_column :orders, :is_lost, :boolean, default: false unless column_exists?(:orders, :is_lost)
    add_column :orders, :should_stay, :boolean, default: false unless column_exists?(:orders, :should_stay)
    add_column :orders, :has_issues, :boolean, default: false unless column_exists?(:orders, :has_issues)
    add_column :orders, :product_name, :text unless column_exists?(:orders, :product_name)
    add_column :orders, :product_number, :string unless column_exists?(:orders, :product_number)
    add_column :orders, :variation, :string unless column_exists?(:orders, :variation)
    add_column :orders, :seller_sku, :string unless column_exists?(:orders, :seller_sku)
    add_column :orders, :shein_sku, :string unless column_exists?(:orders, :shein_sku)
    add_column :orders, :skc, :string unless column_exists?(:orders, :skc)
    add_column :orders, :item_id, :string unless column_exists?(:orders, :item_id)
    add_column :orders, :product_status, :string unless column_exists?(:orders, :product_status)
    add_column :orders, :inventory_id, :string unless column_exists?(:orders, :inventory_id)
    add_column :orders, :exchange_code, :string unless column_exists?(:orders, :exchange_code)
    add_column :orders, :exchange_reason, :text unless column_exists?(:orders, :exchange_reason)
    add_column :orders, :exchange_product_id, :string unless column_exists?(:orders, :exchange_product_id)
    add_column :orders, :is_blocked, :boolean, default: false unless column_exists?(:orders, :is_blocked)
    add_column :orders, :label_print_deadline, :datetime unless column_exists?(:orders, :label_print_deadline)
    add_column :orders, :collection_required_at, :datetime unless column_exists?(:orders, :collection_required_at)
    add_column :orders, :collected_at, :datetime unless column_exists?(:orders, :collected_at)
    add_column :orders, :tracking_code, :string unless column_exists?(:orders, :tracking_code)
    add_column :orders, :last_mile_provider, :string unless column_exists?(:orders, :last_mile_provider)
    add_column :orders, :merchant_package, :boolean, default: false unless column_exists?(:orders, :merchant_package)
    add_column :orders, :passes_through_warehouse, :boolean, default: false unless column_exists?(:orders, :passes_through_warehouse)
    add_column :orders, :first_mile_provider, :string unless column_exists?(:orders, :first_mile_provider)
    add_column :orders, :first_mile_waybill, :string unless column_exists?(:orders, :first_mile_waybill)
    add_column :orders, :seller_currency, :string unless column_exists?(:orders, :seller_currency)
    add_column :orders, :product_price, :decimal, precision: 12, scale: 2 unless column_exists?(:orders, :product_price)
    add_column :orders, :coupon_value, :decimal, precision: 12, scale: 2 unless column_exists?(:orders, :coupon_value)
    add_column :orders, :store_campaign_discount, :decimal, precision: 12, scale: 2 unless column_exists?(:orders, :store_campaign_discount)
    add_column :orders, :commission, :decimal, precision: 12, scale: 2 unless column_exists?(:orders, :commission)

    add_index :orders, :order_type unless index_exists?(:orders, :order_type)

    # ===== PAYMENTS =====
    add_column :payments, :site, :string unless column_exists?(:payments, :site)
    add_column :payments, :related_order_number, :string unless column_exists?(:payments, :related_order_number)
    add_column :payments, :invoice_number, :string unless column_exists?(:payments, :invoice_number)
    add_column :payments, :seller_delivery_date, :date unless column_exists?(:payments, :seller_delivery_date)
    add_column :payments, :delivered_at, :datetime unless column_exists?(:payments, :delivered_at)
    add_column :payments, :invoice_type, :string unless column_exists?(:payments, :invoice_type)
    add_column :payments, :product_price_summary, :decimal, precision: 12, scale: 2 unless column_exists?(:payments, :product_price_summary)
    add_column :payments, :campaign_discount, :decimal, precision: 12, scale: 2 unless column_exists?(:payments, :campaign_discount)
    add_column :payments, :store_coupon_value, :decimal, precision: 12, scale: 2 unless column_exists?(:payments, :store_coupon_value)
    add_column :payments, :payment_commission, :decimal, precision: 12, scale: 2 unless column_exists?(:payments, :payment_commission)
    add_column :payments, :freight_intermediation_fee, :decimal, precision: 12, scale: 2 unless column_exists?(:payments, :freight_intermediation_fee)
    add_column :payments, :storage_operation_fee, :decimal, precision: 12, scale: 2 unless column_exists?(:payments, :storage_operation_fee)
    add_column :payments, :return_processing_fee, :decimal, precision: 12, scale: 2 unless column_exists?(:payments, :return_processing_fee)

    add_index :payments, :invoice_number unless index_exists?(:payments, :invoice_number)
  end
end
